export const UI_TEXT = {
  app: {
    title: 'Photo Editor',
  },
  upload: {
    title: 'Upload Your Photo',
    description: 'Select a JPG, PNG, or WebP image to start editing',
    button: 'Choose Image',
    change: 'Change Image',
  },
  actions: {
    undo: 'Undo',
    redo: 'Redo',
    reset: 'Reset',
  },
  tools: {
    adjustments: 'Adjustments',
    transform: 'Transform',
    crop: 'Crop',
  },
  adjustments: {
    title: 'Adjustments',
    brightness: 'Brightness',
    contrast: 'Contrast',
    saturation: 'Saturation',
  },
  transform: {
    title: 'Transform',
    rotate: 'Rotate',
    rotateLeft: 'Left',
    rotateRight: 'Right',
    flip: 'Flip',
    flipH: 'Horizontal',
    flipV: 'Vertical',
  },
  crop: {
    title: 'Crop',
    aspectRatio: 'Aspect Ratio',
    ratios: {
      free: 'Free',
      original: 'Original',
      square: 'Square (1:1)',
      fourThree: '4:3',
      sixteenNine: '16:9',
    },
    apply: 'Apply Crop',
    clear: 'Clear',
  },
  export: {
    title: 'Export',
    format: 'Format',
    quality: 'Quality',
    download: 'Download',
    exporting: 'Exporting...',
  },
  sessions: {
    title: 'Saved Sessions',
    imageName: 'Image Name',
    placeholder: 'Enter name...',
    recent: 'Recent Edits',
    loading: 'Loading...',
    empty: 'No saved sessions yet',
    load: 'Load',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    setupProfile: 'Setup Profile',
    enterName: 'Enter your name',
    namePlaceholder: 'Your name',
    save: 'Save',
  },
  errors: {
    unsupportedFile: 'Unsupported file type. Please upload a JPG, PNG, or WebP image.',
    loadFailed: 'Failed to load image. Please try again.',
  },
  processing: 'Processing...',
  footer: {
    rights: 'All rights reserved.',
    builtWith: 'Built with',
    using: 'using caffeine.ai',
  },
};
